services:
  chatbot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/chatbot.db
      - OLLAMA_API_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.2:3b
      - PORT=8000
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data: